[2024-12-23T18:28:46.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T18:28:46.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T18:28:41.558185+00:00 [queued]>
[2024-12-23T18:28:46.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T18:28:41.558185+00:00 [queued]>
[2024-12-23T18:28:46.260+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T18:28:46.279+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): simulation_data_with_image_speech> on 2024-12-23 18:28:41.558185+00:00
[2024-12-23T18:28:46.288+0000] {standard_task_runner.py:63} INFO - Started process 1194 to run task
[2024-12-23T18:28:46.291+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'simulation_data_with_image_speech', 'manual__2024-12-23T18:28:41.558185+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_stream.py', '--cfg-path', '/tmp/tmp1qd2d6q6']
[2024-12-23T18:28:46.295+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask simulation_data_with_image_speech
[2024-12-23T18:28:46.367+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.simulation_data_with_image_speech manual__2024-12-23T18:28:41.558185+00:00 [running]> on host 0b4a5bf62610
[2024-12-23T18:28:46.497+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='simulation_data_with_image_speech' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T18:28:41.558185+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T18:28:41.558185+00:00'
[2024-12-23T18:28:46.499+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T18:28:46.725+0000] {logging_mixin.py:188} INFO - Deleted table: green_trip_raw_2024_04_02
[2024-12-23T18:28:46.744+0000] {logging_mixin.py:188} INFO - Created table: green_trip_raw_2024_04_02
[2024-12-23T18:28:46.749+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: connecting to broker:29092 [('172.19.0.4', 29092) IPv4]
[2024-12-23T18:28:46.750+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T18:28:46.752+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: Connection complete.
[2024-12-23T18:28:46.859+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:28:46.860+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:28:46.865+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: connecting to broker:29092 [('172.19.0.4', 29092) IPv4]
[2024-12-23T18:28:46.869+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T18:28:46.871+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: Connection complete.
[2024-12-23T18:28:46.977+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:28:46.978+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:28:46.979+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-23T18:28:47.084+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:28:47.085+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:28:47.096+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: connecting to broker:29092 [('172.19.0.4', 29092) IPv4]
[2024-12-23T18:28:47.097+0000] {conn.py:957} INFO - Probing node 1 broker version
[2024-12-23T18:28:47.099+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.19.0.4', 29092)]>: Connection complete.
[2024-12-23T18:28:47.100+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.19.0.4', 29092)]>: Closing connection. 
[2024-12-23T18:28:47.206+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-23T18:28:47.207+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-23T18:28:47.208+0000] {logging_mixin.py:188} INFO - Connected to Kafka
[2024-12-23T18:28:47.210+0000] {insert_data_to_db.py:136} INFO - Topic raw_image_2024_04_02 already exists. Skipping creation!
[2024-12-23T18:28:47.211+0000] {insert_data_to_db.py:136} INFO - Topic raw_speech_2024_04_02 already exists. Skipping creation!
[2024-12-23T18:28:47.224+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001827. Error: name 'args' is not defined
[2024-12-23T18:28:47.243+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001827. Error: name 'args' is not defined
[2024-12-23T18:28:47.244+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-0 to green_trip_raw_2024_04_02
[2024-12-23T18:28:47.245+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:28:48.247+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:28:49.262+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001828. Error: name 'args' is not defined
[2024-12-23T18:28:49.286+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001828. Error: name 'args' is not defined
[2024-12-23T18:28:49.288+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-1 to green_trip_raw_2024_04_02
[2024-12-23T18:28:49.289+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:28:50.291+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:28:51.304+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001829. Error: name 'args' is not defined
[2024-12-23T18:28:51.327+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001829. Error: name 'args' is not defined
[2024-12-23T18:28:51.333+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-2 to green_trip_raw_2024_04_02
[2024-12-23T18:28:51.334+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:28:52.335+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:28:53.351+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001830. Error: name 'args' is not defined
[2024-12-23T18:28:53.377+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001830. Error: name 'args' is not defined
[2024-12-23T18:28:53.379+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-3 to green_trip_raw_2024_04_02
[2024-12-23T18:28:53.380+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:28:54.381+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:28:55.395+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001831. Error: name 'args' is not defined
[2024-12-23T18:28:55.421+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001831. Error: name 'args' is not defined
[2024-12-23T18:28:55.423+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-4 to green_trip_raw_2024_04_02
[2024-12-23T18:28:55.424+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:28:56.426+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:28:57.436+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001832. Error: name 'args' is not defined
[2024-12-23T18:28:57.456+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001832. Error: name 'args' is not defined
[2024-12-23T18:28:57.457+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-5 to green_trip_raw_2024_04_02
[2024-12-23T18:28:57.458+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:28:58.459+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:28:59.480+0000] {insert_data_to_db.py:197} ERROR - Unexpected error sending file /opt/***/data/image/green_taxi_image.jpg with ID: 20240400001833. Error: name 'args' is not defined
[2024-12-23T18:28:59.499+0000] {insert_data_to_db.py:236} ERROR - Unexpected error sending file /opt/***/data/speech/taxi_conversation.mp3 with ID: 20240400001833. Error: name 'args' is not defined
[2024-12-23T18:28:59.501+0000] {logging_mixin.py:188} INFO - Insert 1 rows file index-6 to green_trip_raw_2024_04_02
[2024-12-23T18:28:59.502+0000] {logging_mixin.py:188} INFO - Waiting for 2 seconds...
[2024-12-23T18:29:00.503+0000] {logging_mixin.py:188} INFO - Waiting for 1 seconds...
[2024-12-23T18:29:01.504+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-23T18:29:01.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-12-23T18:29:01.512+0000] {process_utils.py:132} INFO - Sending 15 to group 1194. PIDs of all processes in the group: [1194]
[2024-12-23T18:29:01.513+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1194
[2024-12-23T18:29:01.515+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T18:29:01.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T18:29:01.529+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stream_processing/insert_data_to_db.py", line 289, in simulate_data_with_image
    send_image_file(args.image_path, producer, _id.iloc[0], args.topic_image)
  File "/opt/airflow/dags/stream_processing/insert_data_to_db.py", line 171, in send_image_file
    with open(file_path, "rb") as f:
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-23T18:29:01.543+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=simulation_data_with_image_speech, run_id=manual__2024-12-23T18:28:41.558185+00:00, execution_date=20241223T182841, start_date=20241223T182846, end_date=20241223T182901
[2024-12-23T18:29:01.567+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 148 for task simulation_data_with_image_speech ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(streaming_pipeline, simulation_data_with_image_speech, manual__2024-12-23T18:28:41.558185+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'simulation_data_with_image_speech', 'dag_id': 'streaming_pipeline', 'run_id': 'manual__2024-12-23T18:28:41.558185+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 12, 23, 18, 28, 46, 248459, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 12, 23, 18, 29, 1, 541503, tzinfo=Timezone('UTC')), 'duration': 15}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1194)
[2024-12-23T18:29:01.607+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1194, status='terminated', exitcode=1, started='18:28:46') (1194) terminated with exit code 1
