[2024-12-24T18:15:29.610+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-24T18:15:29.641+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_batch_visualize.start manual__2024-12-24T18:15:27.596663+00:00 [queued]>
[2024-12-24T18:15:29.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_batch_visualize.start manual__2024-12-24T18:15:27.596663+00:00 [queued]>
[2024-12-24T18:15:29.654+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-24T18:15:29.673+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start> on 2024-12-24 18:15:27.596663+00:00
[2024-12-24T18:15:29.682+0000] {standard_task_runner.py:63} INFO - Started process 3322 to run task
[2024-12-24T18:15:29.684+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline_batch_visualize', 'start', 'manual__2024-12-24T18:15:27.596663+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_batch_visualize.py', '--cfg-path', '/tmp/tmp7zhizswj']
[2024-12-24T18:15:29.687+0000] {standard_task_runner.py:91} INFO - Job 326: Subtask start
[2024-12-24T18:15:29.743+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_batch_visualize.start manual__2024-12-24T18:15:27.596663+00:00 [running]> on host 0b4a5bf62610
[2024-12-24T18:15:29.853+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline_batch_visualize' AIRFLOW_CTX_TASK_ID='start' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T18:15:27.596663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T18:15:27.596663+00:00'
[2024-12-24T18:15:29.855+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-24T18:15:29.875+0000] {pipeline_batch_visualize.py:74} INFO - Start pipeline
[2024-12-24T18:15:29.877+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2024-12-24T18:15:29.879+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-12-24T18:15:29.880+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:15:29.881+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2024-12-24T18:15:29.881+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:15:29.882+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2024-12-24T18:15:29.883+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2024-12-24T18:15:29.884+0000] {logging_mixin.py:188} WARNING - Call stack:
[2024-12-24T18:15:29.893+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2024-12-24T18:15:29.894+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 58, in main
    args.func(args)
[2024-12-24T18:15:29.895+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:15:29.895+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:15:29.896+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2024-12-24T18:15:29.897+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 58, in scheduler
    run_command_with_daemon_option(
[2024-12-24T18:15:29.898+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 85, in run_command_with_daemon_option
    callback()
[2024-12-24T18:15:29.899+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 61, in <lambda>
    callback=lambda: _run_scheduler_job(args),
[2024-12-24T18:15:29.899+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 49, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:15:29.900+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:15:29.901+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:15:29.901+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:15:29.902+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/scheduler_job_runner.py", line 834, in _execute
    self.job.executor.start()
[2024-12-24T18:15:29.903+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 373, in start
    self.impl.start()
[2024-12-24T18:15:29.903+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 312, in start
    worker.start()
[2024-12-24T18:15:29.904+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2024-12-24T18:15:29.905+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2024-12-24T18:15:29.905+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
[2024-12-24T18:15:29.906+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2024-12-24T18:15:29.906+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2024-12-24T18:15:29.907+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
[2024-12-24T18:15:29.907+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 78, in run
    return super().run()
[2024-12-24T18:15:29.908+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2024-12-24T18:15:29.909+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 202, in do_work
    self.execute_work(key=key, command=command)
[2024-12-24T18:15:29.910+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 95, in execute_work
    state = self._execute_work_in_fork(command)
[2024-12-24T18:15:29.911+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 135, in _execute_work_in_fork
    args.func(args)
[2024-12-24T18:15:29.912+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:15:29.913+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:15:29.913+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:15:29.914+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 219, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-12-24T18:15:29.915+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 281, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:15:29.916+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:15:29.916+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:15:29.917+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:15:29.918+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 168, in _execute
    self.task_runner.start()
[2024-12-24T18:15:29.919+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 51, in start
    self.process = self._start_by_fork()
[2024-12-24T18:15:29.919+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 103, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-12-24T18:15:29.920+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:15:29.921+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:15:29.922+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:15:29.922+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 221, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-12-24T18:15:29.923+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 300, in _run_raw_task
    return ti._run_raw_task(
[2024-12-24T18:15:29.923+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:15:29.924+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2024-12-24T18:15:29.924+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-12-24T18:15:29.925+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-12-24T18:15:29.926+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:15:29.927+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:15:29.928+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
[2024-12-24T18:15:29.928+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
[2024-12-24T18:15:29.929+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-12-24T18:15:29.929+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pipeline_batch_visualize.py", line 75, in start_pipeline
    logging.info("Args raw to processed:", args_raw_to_processed)
[2024-12-24T18:15:29.930+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 2216, in info
    root.info(msg, *args, **kwargs)
[2024-12-24T18:15:29.931+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2024-12-24T18:15:29.932+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2024-12-24T18:15:29.933+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2024-12-24T18:15:29.933+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2024-12-24T18:15:29.933+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2024-12-24T18:15:29.934+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 248, in emit
    self.handler.emit(record)
[2024-12-24T18:15:29.935+0000] {logging_mixin.py:188} WARNING - Message: 'Args raw to processed:'
Arguments: (Config(minio_access_key='Xs27nx9M4HgPQ5PXZiUE', minio_secret_key='8iifKZlUZh1NRbepsISUMdg1CxlaIC6OSPQk5X59', endpoint_url='192.168.1.12:9000', jars_dir='/opt/***/jars', taxi_lookup_path='s3a://raw/taxi_lookup.csv', num_output_files=1, green_path_src='s3a://raw/cdc_db/2024/01/01/data', yellow_path_src='s3a://raw/yellow/2024/01/01.parquet', green_path_dist='s3a://processed/data/green/2024/01/01', yellow_path_dist='s3a://processed/data/yellow/2024/01/01'),)
[2024-12-24T18:15:29.935+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2024-12-24T18:15:29.936+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-12-24T18:15:29.937+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:15:29.937+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2024-12-24T18:15:29.938+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:15:29.938+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2024-12-24T18:15:29.938+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2024-12-24T18:15:29.939+0000] {logging_mixin.py:188} WARNING - Call stack:
[2024-12-24T18:15:29.941+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2024-12-24T18:15:29.942+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 58, in main
    args.func(args)
[2024-12-24T18:15:29.943+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:15:29.944+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:15:29.945+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2024-12-24T18:15:29.946+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 58, in scheduler
    run_command_with_daemon_option(
[2024-12-24T18:15:29.946+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 85, in run_command_with_daemon_option
    callback()
[2024-12-24T18:15:29.947+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 61, in <lambda>
    callback=lambda: _run_scheduler_job(args),
[2024-12-24T18:15:29.948+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 49, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:15:29.948+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:15:29.949+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:15:29.950+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:15:29.950+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/scheduler_job_runner.py", line 834, in _execute
    self.job.executor.start()
[2024-12-24T18:15:29.951+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 373, in start
    self.impl.start()
[2024-12-24T18:15:29.951+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 312, in start
    worker.start()
[2024-12-24T18:15:29.952+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2024-12-24T18:15:29.952+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2024-12-24T18:15:29.953+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
[2024-12-24T18:15:29.953+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2024-12-24T18:15:29.954+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2024-12-24T18:15:29.954+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
[2024-12-24T18:15:29.955+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 78, in run
    return super().run()
[2024-12-24T18:15:29.955+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2024-12-24T18:15:29.956+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 202, in do_work
    self.execute_work(key=key, command=command)
[2024-12-24T18:15:29.956+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 95, in execute_work
    state = self._execute_work_in_fork(command)
[2024-12-24T18:15:29.957+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 135, in _execute_work_in_fork
    args.func(args)
[2024-12-24T18:15:29.957+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:15:29.958+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:15:29.959+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:15:29.959+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 219, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-12-24T18:15:29.960+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 281, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:15:29.961+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:15:29.961+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:15:29.962+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:15:29.963+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 168, in _execute
    self.task_runner.start()
[2024-12-24T18:15:29.963+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 51, in start
    self.process = self._start_by_fork()
[2024-12-24T18:15:29.964+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 103, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-12-24T18:15:29.965+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:15:29.965+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:15:29.966+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:15:29.966+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 221, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-12-24T18:15:29.967+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 300, in _run_raw_task
    return ti._run_raw_task(
[2024-12-24T18:15:29.967+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:15:29.968+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2024-12-24T18:15:29.968+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-12-24T18:15:29.969+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-12-24T18:15:29.969+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:15:29.970+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:15:29.970+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
[2024-12-24T18:15:29.970+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
[2024-12-24T18:15:29.971+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-12-24T18:15:29.971+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pipeline_batch_visualize.py", line 76, in start_pipeline
    logging.info("Args spark to bigquery:", args_spark_to_bigquery)
[2024-12-24T18:15:29.972+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 2216, in info
    root.info(msg, *args, **kwargs)
[2024-12-24T18:15:29.973+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2024-12-24T18:15:29.973+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2024-12-24T18:15:29.974+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2024-12-24T18:15:29.974+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2024-12-24T18:15:29.975+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2024-12-24T18:15:29.976+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 248, in emit
    self.handler.emit(record)
[2024-12-24T18:15:29.977+0000] {logging_mixin.py:188} WARNING - Message: 'Args spark to bigquery:'
Arguments: (Config(max_memory='2g', minio_endpoint='192.168.1.12:9000', minio_access_key='Xs27nx9M4HgPQ5PXZiUE', minio_secret_key='8iifKZlUZh1NRbepsISUMdg1CxlaIC6OSPQk5X59', jars_dir='/opt/***/jars', bucket_name='processed', year='2024', month='01', day='01', date='2024-01-01', taxi_lookup_path='s3a://raw/taxi_lookup.csv', bq_project_id='bigdata-445102', bq_dataset_id='data_warehouse', path_auth_file='/opt/***/data/auth_gg_bigquery.json'),)
[2024-12-24T18:15:29.979+0000] {pipeline_batch_visualize.py:82} INFO - Path auth exist
[2024-12-24T18:15:29.979+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-24T18:15:29.980+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-24T18:15:29.992+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline_batch_visualize, task_id=start, run_id=manual__2024-12-24T18:15:27.596663+00:00, execution_date=20241224T181527, start_date=20241224T181529, end_date=20241224T181529
[2024-12-24T18:15:30.020+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-24T18:15:30.048+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-24T18:15:30.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
