[2024-12-24T03:51:26.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-24T03:51:26.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-24T03:51:22.536084+00:00 [queued]>
[2024-12-24T03:51:26.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-24T03:51:22.536084+00:00 [queued]>
[2024-12-24T03:51:26.718+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-24T03:51:26.736+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cdc_spark_streaming_to_datalake> on 2024-12-24 03:51:22.536084+00:00
[2024-12-24T03:51:26.746+0000] {standard_task_runner.py:63} INFO - Started process 5899 to run task
[2024-12-24T03:51:26.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'streaming_pipeline', 'cdc_spark_streaming_to_datalake', 'manual__2024-12-24T03:51:22.536084+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_stream.py', '--cfg-path', '/tmp/tmprn7_v6wx']
[2024-12-24T03:51:26.752+0000] {standard_task_runner.py:91} INFO - Job 181: Subtask cdc_spark_streaming_to_datalake
[2024-12-24T03:51:26.838+0000] {task_command.py:426} INFO - Running <TaskInstance: streaming_pipeline.cdc_spark_streaming_to_datalake manual__2024-12-24T03:51:22.536084+00:00 [running]> on host 0b4a5bf62610
[2024-12-24T03:51:26.976+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='streaming_pipeline' AIRFLOW_CTX_TASK_ID='cdc_spark_streaming_to_datalake' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T03:51:22.536084+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T03:51:22.536084+00:00'
[2024-12-24T03:51:26.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-24T03:51:26.999+0000] {logging_mixin.py:188} INFO - Checking JAR files...:  True
[2024-12-24T03:51:40.980+0000] {spark_streaming_to_dl.py:123} INFO - Spark session successfully created!
[2024-12-24T03:51:40.993+0000] {spark_streaming_to_dl.py:157} INFO - MinIO configuration is created successfully
[2024-12-24T03:51:42.971+0000] {spark_streaming_to_dl.py:176} INFO - Initial dataframe created successfully!
[2024-12-24T03:51:43.505+0000] {logging_mixin.py:188} INFO - root
 |-- vendorid: integer (nullable = true)
 |-- lpep_pickup_datetime: timestamp (nullable = true)
 |-- lpep_dropoff_datetime: timestamp (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- ratecodeid: double (nullable = true)
 |-- pulocationid: integer (nullable = true)
 |-- dolocationid: integer (nullable = true)
 |-- passenger_count: double (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- payment_type: double (nullable = true)
 |-- trip_type: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- id: string (nullable = true)
 |-- id_customer: long (nullable = true)
 |-- rate: double (nullable = true)
[2024-12-24T03:51:43.508+0000] {spark_streaming_to_dl.py:320} INFO - Final dataframe created successfully!
[2024-12-24T03:51:43.512+0000] {spark_streaming_to_dl.py:328} INFO - Streaming is being started...
[2024-12-24T03:55:07.780+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-12-24T03:55:07.787+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-12-24T03:55:07.788+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-12-24T03:55:07.791+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-12-24T03:55:07.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-24T03:55:07.794+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stream_processing/spark_streaming_to_dl.py", line 355, in run_all
    start_steaming(df_final, args.bucket_name, args.year, args.month, args.day)
  File "/opt/airflow/dags/stream_processing/spark_streaming_to_dl.py", line 339, in start_steaming
    return stream_query.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o110.awaitTermination
[2024-12-24T03:55:08.059+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=streaming_pipeline, task_id=cdc_spark_streaming_to_datalake, run_id=manual__2024-12-24T03:51:22.536084+00:00, execution_date=20241224T035122, start_date=20241224T035126, end_date=20241224T035508
[2024-12-24T03:55:08.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 181 for task cdc_spark_streaming_to_datalake (An error occurred while calling o110.awaitTermination; 5899)
[2024-12-24T03:55:08.146+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-24T03:55:08.177+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T03:55:08.182+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
