[2024-12-24T18:25:22.465+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-24T18:25:22.494+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_batch_visualize.start manual__2024-12-24T18:25:20.482531+00:00 [queued]>
[2024-12-24T18:25:22.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_batch_visualize.start manual__2024-12-24T18:25:20.482531+00:00 [queued]>
[2024-12-24T18:25:22.505+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-24T18:25:22.523+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start> on 2024-12-24 18:25:20.482531+00:00
[2024-12-24T18:25:22.530+0000] {standard_task_runner.py:63} INFO - Started process 5646 to run task
[2024-12-24T18:25:22.532+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline_batch_visualize', 'start', 'manual__2024-12-24T18:25:20.482531+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_batch_visualize.py', '--cfg-path', '/tmp/tmpd84s56i9']
[2024-12-24T18:25:22.534+0000] {standard_task_runner.py:91} INFO - Job 332: Subtask start
[2024-12-24T18:25:22.588+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_batch_visualize.start manual__2024-12-24T18:25:20.482531+00:00 [running]> on host 0b4a5bf62610
[2024-12-24T18:25:22.690+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline_batch_visualize' AIRFLOW_CTX_TASK_ID='start' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T18:25:20.482531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T18:25:20.482531+00:00'
[2024-12-24T18:25:22.691+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-24T18:25:22.706+0000] {pipeline_batch_visualize.py:79} INFO - Start pipeline
[2024-12-24T18:25:22.708+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2024-12-24T18:25:22.709+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-12-24T18:25:22.710+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:25:22.711+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2024-12-24T18:25:22.712+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:25:22.713+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2024-12-24T18:25:22.713+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2024-12-24T18:25:22.715+0000] {logging_mixin.py:188} WARNING - Call stack:
[2024-12-24T18:25:22.722+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2024-12-24T18:25:22.723+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 58, in main
    args.func(args)
[2024-12-24T18:25:22.724+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:25:22.724+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:25:22.725+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2024-12-24T18:25:22.725+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 58, in scheduler
    run_command_with_daemon_option(
[2024-12-24T18:25:22.726+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 85, in run_command_with_daemon_option
    callback()
[2024-12-24T18:25:22.727+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 61, in <lambda>
    callback=lambda: _run_scheduler_job(args),
[2024-12-24T18:25:22.728+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 49, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:25:22.729+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:25:22.730+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:25:22.730+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:25:22.731+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/scheduler_job_runner.py", line 834, in _execute
    self.job.executor.start()
[2024-12-24T18:25:22.731+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 373, in start
    self.impl.start()
[2024-12-24T18:25:22.731+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 312, in start
    worker.start()
[2024-12-24T18:25:22.732+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2024-12-24T18:25:22.732+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2024-12-24T18:25:22.733+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
[2024-12-24T18:25:22.733+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2024-12-24T18:25:22.734+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2024-12-24T18:25:22.734+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
[2024-12-24T18:25:22.735+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 78, in run
    return super().run()
[2024-12-24T18:25:22.735+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2024-12-24T18:25:22.735+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 202, in do_work
    self.execute_work(key=key, command=command)
[2024-12-24T18:25:22.736+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 95, in execute_work
    state = self._execute_work_in_fork(command)
[2024-12-24T18:25:22.736+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 135, in _execute_work_in_fork
    args.func(args)
[2024-12-24T18:25:22.737+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:25:22.737+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:25:22.738+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:25:22.739+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 219, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-12-24T18:25:22.740+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 281, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:25:22.740+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:25:22.741+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:25:22.741+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:25:22.742+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 168, in _execute
    self.task_runner.start()
[2024-12-24T18:25:22.742+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 51, in start
    self.process = self._start_by_fork()
[2024-12-24T18:25:22.743+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 103, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-12-24T18:25:22.744+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:25:22.744+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:25:22.745+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:25:22.746+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 221, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-12-24T18:25:22.746+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 300, in _run_raw_task
    return ti._run_raw_task(
[2024-12-24T18:25:22.747+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:25:22.747+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2024-12-24T18:25:22.747+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-12-24T18:25:22.748+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-12-24T18:25:22.748+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:25:22.749+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:25:22.749+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
[2024-12-24T18:25:22.750+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
[2024-12-24T18:25:22.750+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-12-24T18:25:22.751+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pipeline_batch_visualize.py", line 80, in start_pipeline
    logging.info("Args raw to processed:", args_raw_to_processed)
[2024-12-24T18:25:22.751+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 2216, in info
    root.info(msg, *args, **kwargs)
[2024-12-24T18:25:22.751+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2024-12-24T18:25:22.752+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2024-12-24T18:25:22.752+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2024-12-24T18:25:22.752+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2024-12-24T18:25:22.753+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2024-12-24T18:25:22.753+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 248, in emit
    self.handler.emit(record)
[2024-12-24T18:25:22.754+0000] {logging_mixin.py:188} WARNING - Message: 'Args raw to processed:'
Arguments: (Config(minio_access_key='Xs27nx9M4HgPQ5PXZiUE', minio_secret_key='8iifKZlUZh1NRbepsISUMdg1CxlaIC6OSPQk5X59', endpoint_url='192.168.1.12:9000', jars_dir='/opt/***/jars', taxi_lookup_path='s3a://raw/taxi_lookup.csv', num_output_files=1, green_path_src='s3a://raw/cdc_db/2024/01/02/data', yellow_path_src='s3a://raw/yellow/2024/01/02.parquet', green_path_dist='s3a://processed/data/green/2024/01/02', yellow_path_dist='s3a://processed/data/yellow/2024/01/02'),)
[2024-12-24T18:25:22.755+0000] {logging_mixin.py:188} WARNING - --- Logging error ---
[2024-12-24T18:25:22.755+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-12-24T18:25:22.756+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:25:22.756+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2024-12-24T18:25:22.757+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:25:22.757+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2024-12-24T18:25:22.758+0000] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2024-12-24T18:25:22.758+0000] {logging_mixin.py:188} WARNING - Call stack:
[2024-12-24T18:25:22.761+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2024-12-24T18:25:22.762+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 58, in main
    args.func(args)
[2024-12-24T18:25:22.763+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:25:22.763+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:25:22.764+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2024-12-24T18:25:22.764+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 58, in scheduler
    run_command_with_daemon_option(
[2024-12-24T18:25:22.765+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 85, in run_command_with_daemon_option
    callback()
[2024-12-24T18:25:22.765+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 61, in <lambda>
    callback=lambda: _run_scheduler_job(args),
[2024-12-24T18:25:22.766+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 49, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:25:22.766+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:25:22.767+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:25:22.767+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:25:22.767+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/scheduler_job_runner.py", line 834, in _execute
    self.job.executor.start()
[2024-12-24T18:25:22.768+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 373, in start
    self.impl.start()
[2024-12-24T18:25:22.768+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 312, in start
    worker.start()
[2024-12-24T18:25:22.769+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2024-12-24T18:25:22.769+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2024-12-24T18:25:22.769+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
[2024-12-24T18:25:22.770+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2024-12-24T18:25:22.770+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2024-12-24T18:25:22.771+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
[2024-12-24T18:25:22.771+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 78, in run
    return super().run()
[2024-12-24T18:25:22.771+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2024-12-24T18:25:22.772+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 202, in do_work
    self.execute_work(key=key, command=command)
[2024-12-24T18:25:22.772+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 95, in execute_work
    state = self._execute_work_in_fork(command)
[2024-12-24T18:25:22.773+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 135, in _execute_work_in_fork
    args.func(args)
[2024-12-24T18:25:22.773+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:25:22.773+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:25:22.774+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:25:22.774+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 219, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-12-24T18:25:22.775+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 281, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-12-24T18:25:22.775+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:25:22.776+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 402, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-12-24T18:25:22.777+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 431, in execute_job
    ret = execute_callable()
[2024-12-24T18:25:22.777+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 168, in _execute
    self.task_runner.start()
[2024-12-24T18:25:22.778+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 51, in start
    self.process = self._start_by_fork()
[2024-12-24T18:25:22.779+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 103, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-12-24T18:25:22.780+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-12-24T18:25:22.780+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-12-24T18:25:22.781+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 441, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-12-24T18:25:22.781+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 221, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-12-24T18:25:22.782+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 300, in _run_raw_task
    return ti._run_raw_task(
[2024-12-24T18:25:22.782+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-12-24T18:25:22.782+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2024-12-24T18:25:22.783+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-12-24T18:25:22.783+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-12-24T18:25:22.784+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:25:22.784+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2024-12-24T18:25:22.784+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
[2024-12-24T18:25:22.785+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
[2024-12-24T18:25:22.785+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-12-24T18:25:22.785+0000] {logging_mixin.py:188} WARNING -   File "/opt/***/dags/pipeline_batch_visualize.py", line 81, in start_pipeline
    logging.info("Args spark to bigquery:", args_spark_to_bigquery)
[2024-12-24T18:25:22.786+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 2216, in info
    root.info(msg, *args, **kwargs)
[2024-12-24T18:25:22.786+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2024-12-24T18:25:22.786+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2024-12-24T18:25:22.787+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2024-12-24T18:25:22.787+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2024-12-24T18:25:22.788+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2024-12-24T18:25:22.788+0000] {logging_mixin.py:188} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 248, in emit
    self.handler.emit(record)
[2024-12-24T18:25:22.789+0000] {logging_mixin.py:188} WARNING - Message: 'Args spark to bigquery:'
Arguments: (Config(max_memory='2g', minio_endpoint='192.168.1.12:9000', minio_access_key='Xs27nx9M4HgPQ5PXZiUE', minio_secret_key='8iifKZlUZh1NRbepsISUMdg1CxlaIC6OSPQk5X59', jars_dir='/opt/***/jars', bucket_name='processed', year='2024', month='01', day='02', date='2024-01-02', taxi_lookup_path='s3a://raw/taxi_lookup.csv', bq_project_id='bigdata-445102', bq_dataset_id='data_warehouse', path_auth_file='/opt/***/data/auth_gg_bigquery.json'),)
[2024-12-24T18:25:22.791+0000] {pipeline_batch_visualize.py:86} INFO - Path auth exist
[2024-12-24T18:25:22.792+0000] {pipeline_batch_visualize.py:87} INFO - /opt/***/data/auth_gg_bigquery.json
[2024-12-24T18:25:22.792+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-24T18:25:22.793+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-24T18:25:22.804+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline_batch_visualize, task_id=start, run_id=manual__2024-12-24T18:25:20.482531+00:00, execution_date=20241224T182520, start_date=20241224T182522, end_date=20241224T182522
[2024-12-24T18:25:22.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-24T18:25:22.899+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-24T18:25:22.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
